### ISSUE TITLE
core-api: missing array elements in pagination url params

### ISSUE THREAD

**Issue by dated** [Solar-network/core#66]
https://github.com/Solar-network/core/pull/65 is an incomplete fix. While nested params with single values are now transformed correctly, when an array is used as parameter only the last value will be included in the pagination urls. For instance the meta data returned by querying https://sxp.testnet.sh/api/delegates?username=alessio,fun,gym is:

```
{
  "totalCountIsEstimate": false,
  "count": 3,
  "pageCount": 1,
  "totalCount": 3,
  "next": null,
  "previous": null,
  "self": "/delegates?username=gym&page=1&limit=100",
  "first": "/delegates?username=gym&page=1&limit=100",
  "last": "/delegates?username=gym&page=1&limit=100"
}

```

**Comment by alessiodf** [comment]
Closing as fixed in `3.2.4-next.1`.
